FROM node:22-alpine AS deps
WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma ./prisma

RUN npm ci \
 && npx prisma generate

FROM node:22-alpine AS dev
WORKDIR /app

COPY --from=deps /app/node_modules       ./node_modules
COPY --from=deps /app/node_modules/.prisma ./node_modules/.prisma

COPY . .

EXPOSE 3000
CMD ["npm", "run", "start:dev"]
