services:
  db:
    image: postgres:15-alpine
    container_name: url_shortener_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/url_shortener
      JWT_SECRET: your_jwt_secret_here
      PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  studio:
    image: prismagraphql/prisma:latest
    container_name: prisma_studio
    command: studio
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PRISMA_CONFIG: |
        endpoint = "postgresql://postgres:postgres@db:5432/url_shortener"
    ports:
      - '5555:5555'

volumes:
  db_data:
