FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --frozen-lockfile

FROM node:22-alpine AS test

COPY . .

ENV NODE_ENV=test

CMD ["sh", "-c", "npm run test && npm run test:e2e"]
